### ISSUE TITLE
Invalid config for [sensor.resolvbus]: [ttyPort] 

### ISSUE THREAD

**Issue by craggyh** [epenet/hassResolVbus#3]
In HASS I'm seeing the following error when trying to validate the config.

Invalid config for [sensor.resolvbus]: [ttyPort] is an invalid option for [sensor.resolvbus]. Check: sensor.resolvbus->ttyPort.

I checked under HASS.io System and can see /dev/ttyUSB0 listed.
Any ideas?

**Comment by epenet** [comment]
This looks like an issue with your configuration file.
Can you add a note here with the corresponding section of your configuration file?
Could you please also confirm the version of Home Assistant you are using?

**Comment by craggyh** [comment]
Hi

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: time_date
    display_options:
      - 'time'
  -  platform: mqtt
     name: Hot_Water
     state_topic: "hot_water/tele/SENSOR"
     value_template: "{{ value_json['DS18B20']['Temperature'] }}"
     unit_of_measurement: "°C"

  - platform: resolvbus
    name: MyResol
    ttyPort: /dev/ttyUSB0
    filterSource: 0x7321
    filterDestination: 0x0010
    filterCommand: 0x0100
    attributes:
      - name: temperature_sensor_1
        offset: 0
        size: 2
        factor: 0.1
        type: temperature
      - name: system_time
        offset: 18
        size: 2
        type: time
      - name: pump_speed_relay_1
        offset: 10
        size: 1

Using HASS 0.98.1

**Comment by epenet** [comment]
Can you try with the latest from the [dev branch](https://github.com/epenet/hassResolVbus/tree/dev), and confirm it's ok?
If it's OK, I'll merge it into master.

**Comment by craggyh** [comment]
No still the same issue with dev branch.

**Comment by epenet** [comment]
Does your file "custom_components/resolvbus/sensor.py" contain the updated PLATFORMSCHEMA from [4eeed61](https://github.com/epenet/hassResolVbus/commit/4eeed6107ecb7594aca4e0dd4dbc14b857514796#diff-366ff0c6aec0303c239e22f46ac97faa) ?

The dev branch definitely works for me on HASS 0.97.2

**Comment by craggyh** [comment]
It didn't but it does now. Config validated and saved.

Now to figure out how to get a list of sensors/pumps etc. from the Resol device to buld the HASS config.
I used the examples you provided but I just get Temperature 1 None C and Pump 1 None%.
